### ISSUE TITLE
Mark line with an issue in file content display 

### ISSUE THREAD

**Issue by wkonecny** [vgchl/AP-Refactoring#21]
Interface: Code highlighting in Issue detail window

**Comment by vgchl** [comment]
I've searched for a JavaFX component but I only found some very basic Swing based ones. A bit later I stumbled onto [CodeMirror](http://codemirror.net), which looks promising. I'm investigating combining JavaFX with JavaScript a bit further.

**Comment by vgchl** [comment]
Implemented line and text marking for the CodeMirror editor. Specific implementations for strategies (and additional features) will follow later on.
